// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsaychozohyxvnttgqsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzYXljaG96b2h5eHZudHRncXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjY2NDksImV4cCI6MjA3MDI0MjY0OX0.W4zmAdskLEWphyMYDS3bEnfoSAvgmJ-zBVoApmvmHKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});